lines corrected

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,10 +10,10 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Run a one-line script
-        runbdfsks: echo "Hello, CI/CD!"
+        run: echo "Hello, CI/CD!"
         
-      - name: Simulate an error
-       run: echo "About to fail" ; exit 1
+      # - name: Simulate an error
+      #  run: echo "About to fail" ; exit 1
 
       #- name: Another greeting
       #  run: echo "Hello, CI/CD again!"
